### ISSUE TITLE
ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by dlgdwy** [threaTrace-detector/threaTrace#10]
Traceback (most recent call last):
  File "train_streamspot.py", line 591, in <module>
    main()
  File "train_streamspot.py", line 528, in main
    node_num = int(p.stdout.readline())
ValueError: invalid literal for int() with base 10: b''
Has anyone experienced this problem? I would appreciate it if you could provide guidance on resolving it.

**Comment by 814153139** [comment]
Hi,I've encountered the same issue. I would appreciate it if you could  tell me how you solved it.

**Comment by dlgdwy** [comment]
I did not encounter this error when I ran it later, maybe you can run a few more times to try.

**Comment by 814153139** [comment]
> I did not encounter this error when I ran it later, maybe you can run a few more times to try.
OK,thanks!
